spring:
  application:
    name: blogSummer

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sm
    password: sm

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update  # JPA가 테이블을 먼저 생성
    defer-datasource-initialization: true  # ★ data.sql 실행을 JPA 이후로 지연
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always       # ★ data.sql 항상 실행
      encoding: UTF-8    # ★ 인코딩 명시
